#1228 - Update to Node 12.16
mojaloop/central-services-auth pull request #83
Opened 2020-02-12 16:18 UTC by oderayi

- Use node 12.16.o in CircleCI. 
- Updated dependencies

2020-02-12 17:36 UTC, yosheeck submitted a review, later dismissed

2020-02-13 09:12 UTC, rmothilal requested changes
Please see comment

2020-02-13 09:12 UTC, rmothilal commented on package.json
>    "scripts": {
please add dependency check and dependency update to the package.json and make sure that all dependencies are updated

2020-02-13 12:50 UTC, rmothilal commented
As per our conversation @oderayi will be updating the library to cater for the new error framework, this process will take some time

2020-02-13 14:32 UTC, rmothilal approved these changes
happy, this repo will bbe archieved

2020-02-13 14:43 UTC, merged